import RainbowKitAndWagmiProvider from "./RainbowKitAndWagmiProvider"
import "./globals.css"
import { Inter as FontSans } from "next/font/google";
import Layout from "@/components/shared/Layout";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/shared/app-sidebar"
import { cookies } from "next/headers"
import { cn } from "@/lib/utils"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout ({ children }) {

  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="eng" suppressHydrationWarning>
      <head />
      <body 
      className={cn("min-h-screen bg-background font-sans antialiased dark",
      fontSans.variable)}
      suppressHydrationWarning={true}
  >
    <RainbowKitAndWagmiProvider>
      <Layout>
      <SidebarProvider defaultOpen={defaultOpen}>
      <AppSidebar />
      <main>
        <SidebarTrigger />
        {children}
      </main>
    </SidebarProvider>
      </Layout>
    </RainbowKitAndWagmiProvider>
  </body>
    </html>
  )
}
