name: ChainLend Action

on:
  push:
    branches: [main]

jobs:
  tests:
    name: Smart Contracts Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.19.2
        uses: actions/setup-node@v1
        with:
          node-version: 20.19.2

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: 'backend/node_modules'
          key: node_modules-${{ hashFiles('backend/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Tests
        working-directory: ./backend 
        run: npx hardhat test